version: '3.8'
services:
  postgres:
    container_name: queue-pg
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: main_db
      POSTGRES_HOST: localhost
      POSTGRES_PORT: "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  spotify:
    build: ./spotify
    ports:
      - "8000:8000"
    environment:
      SPOTIPY_CLIENT_ID: your_spotify_client_id
      SPOTIPY_CLIENT_SECRET: your_spotify_client_secret
      SERVICE_PORT: "8000"
    depends_on:
      - postgres
  queue:
    build: ./queue
    ports:
      - "8081:8081"
    environment:
      SERVICE_PORT: "8081"
    depends_on:
      - postgres
  stream_ffmpeg:
    build: ./stream_ffmpeg
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      SERVICE_PORT: "8082"
      ROUT_TELEGRAM_TYPE: rtmps
      ROUT_TELEGRAM_CODEC: aac
      ROUT_TELEGRAM_PATH: rtmps://dc4-1.rtmp.t.me/s/id:key

      ROUT_HLS_TYPE: hls
      ROUT_HLS_CODEC: aac
      ROUT_HLS_PATH: /var/www/html/radio

      ROUT_AAC_TYPE: aac
      ROUT_AAC_CODEC: aac
      ROUT_AAC_PATH: /var/www/html/radio
volumes:
  postgres-data:
