services:
  postgres:
    container_name: queue-pg
    image: postgres
    hostname: localhost
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: main_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  main:
    build: ./main
    ports:
      - "8082:8082"
    environment:
      DB_URL: postgresql://admin:root@queue-pg:5432/main_db
    depends_on:
      - postgres
  spotify:
    build: ./spotify
    ports:
      - "7003:7003"
    environment:
      SPOTIPY_CLIENT_ID: your_spotify_client_id
      SPOTIPY_CLIENT_SECRET: your_spotify_client_secret
    depends_on:
      - postgres
  queue:
    build: ./queue
    ports:
      - "7002:7002"
    environment:
      DB_URL: postgresql://admin:root@queue-pg:5432/main_db
    depends_on:
      - postgres
  stream_ffmpeg:
    build: ./stream_ffmpeg
    ports:
      - "7001:7001"
    depends_on:
      - queue
    environment:
      ROUT_TELEGRAM_TYPE: rtmps
      ROUT_TELEGRAM_CODEC: aac
      ROUT_TELEGRAM_PATH: rtmps://dc4-1.rtmp.t.me/s/id:key

      ROUT_HLS_TYPE: hls
      ROUT_HLS_CODEC: aac
      ROUT_HLS_PATH: /var/www/html/radio

      ROUT_AAC_TYPE: aac
      ROUT_AAC_CODEC: aac
      ROUT_AAC_PATH: /var/www/html/radio
volumes:
  postgres-data:
