version: '3.8'
services:
  postgres:
    container_name: queue-pg
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: main_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  spotify:
    build: ./spotify
    ports:
      - "8000:8000"
    environment:
      SPOTIPY_CLIENT_ID: your_spotify_client_id
      SPOTIPY_CLIENT_SECRET: your_spotify_client_secret
    depends_on:
      - postgres
  queue:
    build: ./queue
    ports:
      - "8081:8081"
    depends_on:
      - postgres
volumes:
  postgres-data:
